<?php

/**
 * Groups configuration for default Minify implementation
 * @package Minify
 */
/**
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/min/builder/
 *
 * See https://github.com/mrclay/minify/blob/master/docs/CustomServer.wiki.md for other ideas
 * */
return array(
    'datatableButtonsJs' => array(
        '//lib/datatables/js/buttons/dataTables.buttons.min.js',
        '//lib/datatables/js/buttons/buttons.bootstrap4.min.js',
        '//lib/datatables/js/buttons/jszip.min.js',
        '//lib/datatables/js/buttons/pdfmake.min.js',
        '//lib/datatables/js/buttons/vfs_fonts.js',
        '//lib/datatables/js/buttons/buttons.colVis.min.js',
        '//lib/datatables/js/buttons/buttons.html5.min.js',
        '//lib/datatables/js/buttons/buttons.print.min.js',
    ),
    'datatableSelectJs' => array(
        '//lib/datatables/js/Select-1.3.3/js/dataTables.select.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.bootstrap4.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.bulma.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.dataTables.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.foundation.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.jqueryui.min.js',
        '//lib/datatables/js/Select-1.3.3/js/select.semanticui.min.js',
    ),
    'datatableSelectCss' => array(
        '//lib/datatables/js/Select-1.3.3/css/dataTables.select.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.bootstrap4.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.bulma.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.dataTables.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.foundation.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.jqueryui.min.css',
        '//lib/datatables/js/Select-1.3.3/css/select.semanticui.min.css',
    ),
    'consultaCss' => array(
        '//vendor/twbs/bootstrap/dist/css/bootstrap.min.css',
        '//lib/font-awesome/css/font-awesome.min.css',
        '//lib/ladda/css/ladda-themeless.min.css',
        '//lib/select2/css/select2.min.css',
        '//lib/select2/css/select2-bootstrap4.min.css',
        '//lib/datatables/css/dataTables.bootstrap4.min.css',
        '//lib/pace/css/pace.css',
        '//assets/css/custom.css',
        '//assets/css/app.css',
        '//assets/css/consulta.css',
    ),
    'consultaJs' => array(
        '//lib/jquery/jquery.min.js',
        '//lib/jquery-ui/js/jquery-ui.min.js',
        '//lib/popper.min.js',
        '//vendor/twbs/bootstrap/dist/js/bootstrap.bundle..min.js',
        '//vendor/twbs/bootstrap/dist/js/bootstrap.min.js',
        '//lib/jquery/jquery.form.js',
        '//lib/bootbox.min.js',
        '//lib/datatables/js/jquery.dataTables.min.js',
        '//lib/datatables/js/dataTables.bootstrap4.min.js',
        '//lib/jquery.mask.min.js',
        '//lib/jquery-validate/jquery.validate.min.js',
        '//lib/jquery-validate/additional-methods.min.js',
        '//lib/jquery-validate/messages_pt_BR.min.js',
        '//lib/ladda/js/spin.min.js',
        '//lib/ladda/js/ladda.min.js',
        '//lib/pace/js/pace.min.js',
        '//lib/select2/js/select2.full.min.js',
        '//lib/select2/js/i18n/pt-BR.js',
        '//assets/js/consulta.js'
    ),
    'contribuinteLoginCss' => array(
        '//vendor/twbs/bootstrap/dist/css/bootstrap.min.css',
        '//lib/font-awesome/css/font-awesome.min.css',
        '//lib/ladda/css/ladda-themeless.min.css',
        '//lib/pace/css/pace.css',
        '//assets/css/body_blue.css',
        '//assets/css/processo_externo_login.css',
        '//assets/css/message.css'
    ),
    'contribuinteLoginJs' => array(
        '//lib/jquery/jquery.min.js',
        '//lib/jquery-ui/js/jquery-ui.min.js',
        '//lib/jquery/jquery.form.js',
        '//lib/popper.min.js',
        '//lib/jquery.mask.min.js',
        '//vendor/twbs/bootstrap/dist/js/bootstrap.min.js',
        '//lib/jquery-validate/jquery.validate.min.js',
        '//lib/jquery-validate/messages_pt_BR.min.js',
        '//lib/pace/js/pace.min.js',
        '//lib/bootbox.min.js',
        '//lib/ladda/js/spin.min.js',
        '//lib/ladda/js/ladda.min.js',
        '//lib/bootstrap-growl-master/jquery.bootstrap-growl.min.js',
        '//lib/jquery-ui/js/lang/datepicker-pt-BR.js',
        '//assets/js/view/contribuinte/login.js'
    ),
    'loginCss' => array(
        '//vendor/twbs/bootstrap/dist/css/bootstrap.min.css',
        '//lib/font-awesome/css/font-awesome.min.css',
        '//lib/ladda/css/ladda-themeless.min.css',
        '//lib/pace/css/pace.css',
        '//assets/css/login.css',
        '//assets/css/message.css'
    ),
    'loginJs' => array(
        '//lib/jquery/jquery.min.js',
        '//lib/popper.min.js',
        '//vendor/twbs/bootstrap/dist/js/bootstrap.min.js',
        '//lib/jquery-validate/jquery.validate.min.js',
        '//lib/jquery-validate/messages_pt_BR.min.js',
        '//lib/pace/js/pace.min.js',
        '//lib/bootbox.min.js',
        '//lib/ladda/js/spin.min.js',
        '//lib/ladda/js/ladda.min.js',
        '//lib/bootstrap-growl-master/jquery.bootstrap-growl.min.js',
        '//lib/jquery.mask.min.js',
        '//assets/js/login.js',
    ),
    'pluginsJs' => array(
        '//lib/jquery/jquery.min.js',
        '//lib/jquery-ui/js/jquery-ui.min.js',
        '//lib/jquery/jquery.form.js',
        '//lib/jquery-ui/js/lang/datepicker-pt-BR.js',
        '//lib/popper.min.js',
        '//vendor/twbs/bootstrap/dist/js/bootstrap.min.js',
        '//lib/bootstrap-growl-master/jquery.bootstrap-growl.min.js',
        '//lib/pace/js/pace.min.js',
        '//lib/ladda/js/spin.min.js',
        '//lib/ladda/js/ladda.min.js',
        '//lib/select2/js/select2.full.min.js',
        '//lib/jstree/jstree.min.js',
        '//lib/select2/js/select2totree.js',
        '//lib/select2/js/i18n/pt-BR.js',
        '//lib/jquery-validate/jquery.validate.min.js',
        '//lib/jquery-validate/additional-methods.min.js',
        '//lib/jquery-validate/messages_pt_BR.min.js',
        '//lib/datatables/js/jquery.dataTables.min.js',
        '//lib/datatables/js/dataTables.bootstrap4.min.js',
        '//vendor/kartik-v/bootstrap-fileinput/js/fileinput.min.js',
        '//vendor/kartik-v/bootstrap-fileinput/js/locales/pt-BR.js',
        '//vendor/kartik-v/bootstrap-fileinput/themes/fa/theme.min.js',
        '//lib/lightbox/js/lightbox.min.js',
        '//lib/jquery.cookie.min.js',
        '//lib/bootbox.min.js',
        '//lib/jquery.mask.min.js',
        '//lib/jquery.bootstrap.wizard.min.js',
        '//lib/autoNumeric.js',
        '//lib/highcharts/code/highcharts.js',
        '//lib/highcharts/code/modules/data.js',
        '//lib/highcharts/code/modules/exporting.js',
        '//lib/tinymce/tinymce.min.js',
        '//lib/pdf-lib.min.js'
    ),
    'pluginsCss' => array(
        '//lib/font-awesome/css/font-awesome.min.css',
        '//lib/ladda/css/ladda-themeless.min.css',
        '//lib/lightbox/css/lightbox.min.css',
        '//lib/pace/css/pace.css',
        '//lib/select2/css/select2.min.css',
        '//lib/select2/css/select2totree.css',
        '//lib/jstree/themes/default/style.min.css',
        '//lib/datatables/css/dataTables.bootstrap4.min.css',
        '//vendor/twbs/bootstrap/dist/css/bootstrap.min.css',
        '//lib/jquery-ui/css/jquery-ui.min.css',
        '//vendor/kartik-v/bootstrap-fileinput/css/fileinput.min.css',
        '//assets/css/app.css',
        '//assets/css/message.css'
    )
);

