name: continuous deployment
on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'lxtec'
          server: '207.244.248.118'
          port: 37950
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./* # default is ./*
          remote_path: 'var/www/html/LxProcessos/demoprcss/html'
          args: '-o ConnectTimeout=5'
